name=input("please enter your name :")
print(name)
surname=input("please enter your surname :")
print(surname)
age=int(input("please enter your age :"))
print(age)
city=input("please enter your city :")
print(city)